version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  playwright:
    docker:
       - image: mcr.microsoft.com/playwright:v1.44.0-jammy
  node:
    docker:
      - image: cimg/node:22.1

jobs:
  app-unit:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn workspace app test:unit:ci

workflows:
  test:
    jobs:
      - app-unit
